# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: clima_lecturas_api
      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  python_app:
    build:
      context: .
    restart: always
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/usr/src/app